jdbc.url=jdbc:presto://presto-coordinator:8080/iceberg/knowledge_graph
jdbc.driver=com.facebook.presto.jdbc.PrestoDriver
jdbc.user=admin

# Enable SQL translation logging
logging.level.it.unibz.inf.ontop=DEBUG
logging.level.it.unibz.inf.ontop.answering.reformulation=DEBUG